#!/usr/bin/env python3
"""Build Week 2 slides for Human and Machine Learning SP26.

Style: SP25-style sequential-reveal math build-ups. Each equation appears
piece-by-piece across sequential slides (one slide = one new line revealed),
implemented via `SDSDeck.build_slides(title, steps, notes)`.

Real figures (bell curves, Binomial PMF) are pre-generated by
`generate_images.py` into `images/` and embedded via
`SDSDeck.content_image_slide()`.

Produces:
- slides/sp26/week2-slides.pptx
- week2-speaker-notes.md (regenerated)
"""

import argparse
from pathlib import Path

from sds_slides import SDSDeck

HERE = Path(__file__).parent
IMG = HERE / "images"
PPTX_OUT = HERE / "slides" / "sp26" / "week2-slides.pptx"
PREVIEW_OUT = HERE / "slides" / "sp26" / "preview"
NOTES_OUT = HERE / "week2-speaker-notes.md"

parser = argparse.ArgumentParser()
parser.add_argument("--preview", action="store_true",
                    help="Also render per-slide PNGs into slides/sp26/preview/")
parser.add_argument("--dpi", type=int, default=150,
                    help="Preview render DPI (default 150)")
args = parser.parse_args()

deck = SDSDeck(course_label="Human and Machine Learning SP26 — Week 2")

AGENDA = [
    ("Welcome + meet Chibany",       "0:00"),
    ("Marr's three levels",           "0:08"),
    ("Notation lock-in",              "0:15"),
    ("Joint + marginalization",       "0:18"),
    ("Expected value + discrete",     "0:30"),
    ("Continuous prob + Gaussian",    "0:45"),
    ("Break",                         "1:05"),
    ("Gaussian-Gaussian update",      "1:15"),
    ("Paper presentations",           "1:40"),
    ("Admin + Week 3",                "1:50"),
]

# ============================================================
# TITLE
# ============================================================

deck.title_slide(
    title="Week 2 — Levels of Analysis + Bayes Continued",
    subtitle="Friday, April 24, 2026",
    authors="Prof. Joseph Austerweil",
    notes=(
        "Crisp start. Today's backbone is the second half: continuous "
        "probability, Gaussian, and the Gaussian-Gaussian update. Marr is "
        "a 7-min frame; Chibany meets us at the top."
    ),
)

# ============================================================
# BLOCK 1 — Welcome back + meet Chibany (8 min total: 3 syllabus + 5 Chibany)
# ============================================================

deck.agenda_slide(AGENDA, highlight="Welcome + meet Chibany")

deck.section_break(
    segment_name="Welcome back + meet Chibany",
    notes=(
        "~8 min. First 3 min: syllabus updates + Week 1 pulse. Next 5 min: "
        "introduce Chibany and the bento scenario properly, so the rest of "
        "the session has a narrative it can actually lean on."
    ),
)

deck.content_slide(
    title="Two changes since Week 1",
    body=[
        ("Paper presentations are in.",
         {"size": 26, "bold": True}),
        ("Each of you presents one reading once. More at 1:40.",
         {"size": 20, "color": deck.DIM}),
        ("", {"size": 10}),
        ("Reflections: 6 of 12, not 8 of 13.",
         {"size": 26, "bold": True}),
        ("Class is now 2 h × 12 weeks. More at 1:50.",
         {"size": 20, "color": deck.DIM}),
    ],
    notes=(
        "State the two facts, move on. If a student asks for detail, say "
        "'I'll get to that at 1:40 / 1:50.' ~1 min."
    ),
)

# ---- Meet Chibany ----
deck.build_slides(
    title="Meet Chibany",
    steps=[
        [
            ("Chibany is a probability-minded professor at our school.",
             {"size": 22}),
            ("Every day, students bring them bentos.",
             {"size": 22}),
            ("", {"size": 12}),
            ("Chibany is the protagonist of our textbook,",
             {"size": 20, "color": deck.DIM}),
            ("\"A Narrative Introduction to Probability\" — Tutorial 3 Ch 1.",
             {"size": 20, "color": deck.DIM}),
        ],
        [
            ("", {"size": 10}),
            ("There's a catch:   the bento boxes are OPAQUE.",
             {"size": 24, "bold": True, "color": deck.YELLOW}),
            ("", {"size": 6}),
            ("Chibany can't peek. They want to know the meal — without opening.",
             {"size": 22}),
        ],
        [
            ("", {"size": 8}),
            ("What Chibany knows  (from past semesters):",
             {"size": 22, "bold": True}),
            ("   • Tonkatsu bentos weigh about 500 g",
             {"size": 22, "color": deck.ACCENT}),
            ("   • Hamburger bentos weigh about 350 g",
             {"size": 22, "color": deck.ACCENT}),
            ("   • Students bring tonkatsu about 70% of the time",
             {"size": 22, "color": deck.ACCENT}),
            ("     (overheard two students chatting last week)",
             {"size": 18, "color": deck.DIM}),
        ],
        [
            ("", {"size": 8}),
            ("Chibany's plan:   WEIGH THE BENTO.",
             {"size": 24, "bold": True, "color": deck.YELLOW}),
            ("", {"size": 6}),
            ("\"If the weight doesn't tell me for sure, it'll at least UPDATE",
             {"size": 22, "color": deck.ACCENT, "italic": True}),
            (" my belief about today's meal.\"",
             {"size": 22, "color": deck.ACCENT, "italic": True}),
            ("", {"size": 8}),
            ("That update is Bayes' rule. Same rule as last week — new anchor.",
             {"size": 20, "color": deck.DIM}),
        ],
    ],
    notes=[
        "Slide 1: 'Before we do math, meet Chibany. They're the character we'll "
        "use as our worked example all semester. They\\'re also the protagonist "
        "of the textbook, so reading T3 Ch 1 tonight will top this up.'",
        "Slide 2: 'The hook: opaque bentos. Chibany can\\'t directly see the meal. "
        "Classic hidden-variable setup. Just like last week\\'s checkershadow and "
        "Heider-Simmel — an inference problem under incomplete information.'",
        "Slide 3: 'Prior knowledge. Two canonical weights and a 70/30 prior on "
        "the meal. Note the prior comes from the world (overheard conversation), "
        "not from nowhere — priors are usually knowledge from somewhere else.'",
        "Slide 4: 'Chibany\\'s strategy: weigh the bento and update. This is the "
        "Week 1 sick-friend move, just with a bento instead of a patient. Prior "
        "belief, observation, posterior. Same rule. New anchor.'",
    ],
)

# ============================================================
# BLOCK 2 — Marr's three levels (7 min, trimmed)
# ============================================================

deck.agenda_slide(AGENDA, highlight="Marr's three levels")

deck.section_break(
    segment_name="Marr's three levels — frame for the whole course",
    notes=(
        "7 min hard cap. Trimmed from the earlier draft to free time for "
        "Gaussian visualization. 3 slides (one per level) + check-in. Do "
        "NOT let this expand."
    ),
)

deck.content_slide(
    title="Marr L1 — what problem is being solved?",
    body=[
        ("For Chibany:   Compute  P(meal | weight).",
         {"size": 24, "bold": True, "color": deck.ACCENT}),
        ("", {"size": 8}),
        ("L1 specifies the CORRECT computation — not how to do it,",
         {"size": 20, "color": deck.DIM}),
        ("not how Chibany's brain actually does it.",
         {"size": 20, "color": deck.DIM}),
        ("", {"size": 8}),
        ("Different goal  ⇒  different L1  ⇒  different normative answer.",
         {"size": 22, "bold": True}),
    ],
    notes=(
        "~2 min. Bayes is the normative answer for 'combine prior + evidence.' "
        "Counterfactual: if the goal were 'minimize reaction time,' L1 differs. "
        "Choosing L1 IS a modeling move."
    ),
)

deck.content_slide(
    title="Marr L2 — what algorithm?",
    body=[
        ("Same L1 — multiple algorithms:",
         {"size": 22, "bold": True}),
        ("", {"size": 6}),
        ("  • Enumerate  (today: 2 hypotheses, sum-and-normalize)",
         {"size": 20}),
        ("  • Sample  (Week 7 Monte Carlo)",
         {"size": 20}),
        ("  • \"Always guess tonkatsu\"  —  an algorithm. A BAD one.",
         {"size": 20, "color": deck.RED}),
        ("", {"size": 8}),
        ("Bayes is L1. Algorithms are L2.",
         {"size": 22, "bold": True, "color": deck.ACCENT}),
    ],
    notes=(
        "~2 min. The bad-algorithm point is important: \"always guess tonkatsu\" "
        "is 70% accurate because of the prior — it's still a well-defined L2, "
        "just one that ignores the observation."
    ),
)

deck.content_slide(
    title="Marr L3 — what implementation?",
    body=[
        ("Chibany:  neurons, experience, gut feeling.",
         {"size": 22}),
        ("Our simulation:  JAX arrays, floating-point math, Colab.",
         {"size": 22}),
        ("", {"size": 8}),
        ("Three levels — mostly independent.",
         {"size": 22, "bold": True}),
        ("Right L1 + wrong L2 → systematic human biases.",
         {"size": 22, "color": deck.ACCENT}),
        ("(Full L3 treatment: Week 11, Deep NNs.)",
         {"size": 18, "color": deck.DIM, "italic": True}),
    ],
    notes=(
        "~2 min. FAST. Land the independence point — this is the thread for "
        "the rest of the course."
    ),
)

deck.content_slide(
    title="Check-in — the cab problem",
    body=[
        ("Last week: witness says \"blue\"; 15% blue cabs;",
         {"size": 22}),
        ("witness accurate 80%.  Most of you guessed ~80%.",
         {"size": 22}),
        ("", {"size": 8}),
        ("At which level was the mistake?",
         {"size": 26, "bold": True, "color": deck.YELLOW}),
        ("", {"size": 6}),
        ("Target: L1 = P(blue | report). Actual L1 answer ≈ 0.41.",
         {"size": 20, "color": deck.DIM, "italic": True}),
        ("80% is a wrong-L2 claim  (ignore the base rate).",
         {"size": 20, "color": deck.DIM, "italic": True}),
    ],
    notes=(
        "~1 min. Fast — elicit the answer. Bridge: \"humans systematically use "
        "a non-Bayesian L2 on this problem; that gap between L1 and L2 is "
        "behavioral economics.\""
    ),
)

# ============================================================
# BLOCK 3 — Notation lock-in (3 min)
# ============================================================

deck.agenda_slide(AGENDA, highlight="Notation lock-in")

deck.section_break(
    segment_name="Notation lock-in",
    notes="3 min. Quick. No theatrical apology.",
)

deck.build_slides(
    title="Notation — one rule, starting today",
    steps=[
        [
            ("From today:",
             {"size": 20, "color": deck.DIM}),
            ("", {"size": 12}),
            ("H = hypothesis  (hidden — what we want to know)",
             {"size": 26, "bold": True, "color": deck.YELLOW}),
            ("D = data  (observed — what we see)",
             {"size": 26, "bold": True, "color": deck.YELLOW}),
            ("", {"size": 8}),
            ("For Chibany:   H = meal,   D = weight.",
             {"size": 22, "color": deck.ACCENT}),
        ],
        [
            ("", {"size": 12}),
            ("P(H = h | D = d)  =  P(D = d | H = h) · P(H = h)  /  P(D = d)",
             {"size": 22, "bold": True}),
        ],
        [
            ("", {"size": 6}),
            ("  posterior     =      likelihood     ·    prior    /   evidence",
             {"size": 16, "color": deck.DIM}),
        ],
    ],
    notes=[
        "Slide 1: 'H = hypothesis, D = data. For Chibany, H is the meal, D is "
        "the weight. Simple, consistent.'",
        "Slide 2: 'The formula you saw last week. Same one.'",
        "Slide 3: 'Name the four pieces. You\\'ll see these names the rest of "
        "the semester.'",
    ],
)

# ============================================================
# BLOCK 4 — Joint + marginalization, Chibany-style (12 min)
# ============================================================

deck.agenda_slide(AGENDA, highlight="Joint + marginalization")

deck.section_break(
    segment_name="Joint + marginalization — Chibany-style",
    notes=(
        "12 min. Three build-ups + a Week-1 bridge slide. Now in H/D notation "
        "with Chibany — students saw these moves last week in the 2-coin-flip "
        "grid and in the sick-friend/cab problems."
    ),
)

# Week-1 bridge slide (sick-friend in H/D notation)
deck.build_slides(
    title="Last week's sick-friend problem, in H/D notation",
    steps=[
        [
            ("Last week:   smoker friend, cough heard, three hypotheses.",
             {"size": 20, "color": deck.DIM}),
            ("", {"size": 8}),
            ("In the new notation:",
             {"size": 22}),
            ("   H ∈ { cold, stomach virus, lung cancer }",
             {"size": 22}),
            ("   D = cough",
             {"size": 22}),
        ],
        [
            ("", {"size": 6}),
            ("   Prior      P(H):      0.45     0.10     0.10",
             {"size": 20}),
            ("   Likelihood P(D|H):  0.90     0.45     0.90",
             {"size": 20}),
            ("", {"size": 4}),
            ("   Numerators:          0.405   0.045   0.090",
             {"size": 20}),
            ("   Evidence P(D) = 0.540",
             {"size": 20}),
        ],
        [
            ("", {"size": 4}),
            ("   Posteriors:           0.75     0.083    0.167",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
            ("", {"size": 8}),
            ("Same answer as last week. Same rule. New labels.",
             {"size": 22, "color": deck.YELLOW}),
            ("Everything we do today uses this SAME structure.",
             {"size": 20, "color": deck.DIM}),
        ],
    ],
    notes=[
        "Slide 1: 'Quick re-cast. H = disease hypothesis (note: lowercase h "
        "from last week is now uppercase H; content unchanged). D = cough. "
        "Same problem, new notation.'",
        "Slide 2: 'Same numbers as last week. Prior, likelihood, multiply, sum '"
        "for the evidence.'",
        "Slide 3: 'Posterior 0.75 / 0.083 / 0.167. Cold wins despite smoking "
        "— priors matter, likelihoods matter, neither alone is enough. Now "
        "today: same structure, but with Chibany.'",
    ],
)

deck.content_slide(
    title="Setup — two-by-two Chibany world",
    body=[
        ("Start simple: discretize weight to TWO buckets.",
         {"size": 22}),
        ("", {"size": 6}),
        ("   H ∈ {tonkatsu, hamburger}",
         {"size": 22}),
        ("   D ∈ {heavy, light}",
         {"size": 22}),
        ("", {"size": 10}),
        ("Prior:    P(tonkatsu) = 0.7,   P(hamburger) = 0.3",
         {"size": 22}),
        ("Likelihood:   P(heavy | tonkatsu) = 0.9,   P(heavy | hamburger) = 0.2",
         {"size": 22}),
        ("", {"size": 8}),
        ("Later (Block 6): continuize weight. For now, 2×2.",
         {"size": 18, "color": deck.DIM, "italic": True}),
    ],
    notes=(
        "~1 min. The 2×2 is the scaffolding. Structurally the same as last "
        "week\\'s 2-coin-flip grid {HH, HT, TH, TT} — same moves apply. The "
        "difference: different numbers, and meal ≠ weight (two variables, not "
        "the same coin twice)."
    ),
)

# Joint build-up
deck.build_slides(
    title="The joint  P(H, D)  — build the 2×2 table",
    steps=[
        [
            ("Four cells:",
             {"size": 22}),
            ("", {"size": 6}),
            ("                   |   heavy   |   light",
             {"size": 20}),
            ("   tonkatsu    |     ?     |     ?",
             {"size": 20}),
            ("   hamburger |     ?     |     ?",
             {"size": 20}),
        ],
        [
            ("", {"size": 10}),
            ("Joint by the product rule:    P(H, D)  =  P(D | H) · P(H)",
             {"size": 20, "bold": True}),
            ("", {"size": 4}),
            ("   P(tonk, heavy)   =  0.9 · 0.7  =  0.63",
             {"size": 20}),
            ("   P(tonk, light)    =  0.1 · 0.7  =  0.07",
             {"size": 20}),
            ("   P(hamb, heavy)  =  0.2 · 0.3  =  0.06",
             {"size": 20}),
            ("   P(hamb, light)   =  0.8 · 0.3  =  0.24",
             {"size": 20}),
        ],
        [
            ("", {"size": 6}),
            ("Sanity check:   0.63 + 0.07 + 0.06 + 0.24  =  1.00  ✓",
             {"size": 22, "bold": True, "color": deck.GREEN}),
            ("", {"size": 4}),
            ("Recognize the shape?  Week 1's 2-coin-flip grid had 4 cells too.",
             {"size": 18, "color": deck.DIM, "italic": True}),
            ("Different numbers, same structure.",
             {"size": 18, "color": deck.DIM, "italic": True}),
        ],
    ],
    notes=[
        "Slide 1: 'Four combinations of (meal, weight). We want the joint "
        "probability of each.'",
        "Slide 2: 'Joint = prior times conditional. Multiply across.'",
        "Slide 3: 'Sanity check. Sum to 1. Analogy to last week\\'s {HH, HT, "
        "TH, TT} — the structure is the same; we\\'re just working with "
        "asymmetric probabilities.'",
    ],
)

# Marginalization build-up
deck.build_slides(
    title="Marginalization — sum over what you don't care about",
    steps=[
        [
            ("P(heavy)  =  ?",
             {"size": 24, "bold": True}),
            ("", {"size": 8}),
            ("Sum the joint over H:",
             {"size": 22}),
            ("   P(heavy)  =  P(tonk, heavy)  +  P(hamb, heavy)",
             {"size": 22}),
            ("               =  0.63  +  0.06   =   0.69",
             {"size": 24, "bold": True, "color": deck.ACCENT}),
        ],
        [
            ("", {"size": 10}),
            ("P(light)  =  0.07 + 0.24  =  0.31",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
            ("   0.69 + 0.31 = 1 ✓",
             {"size": 20, "color": deck.DIM}),
        ],
        [
            ("", {"size": 10}),
            ("The named move:  MARGINALIZATION.",
             {"size": 24, "bold": True, "color": deck.YELLOW}),
            ("Given the joint, sum over the variable you're not asking about.",
             {"size": 22}),
            ("Week 1 called this the sum rule.",
             {"size": 20, "color": deck.DIM}),
        ],
    ],
    notes=[
        "Slide 1: 'What\\'s P(heavy) unconditionally? The bento is heavy either "
        "because it\\'s a heavy tonkatsu OR a heavy hamburger. Sum across H.'",
        "Slide 2: 'And P(light). Check it sums to 1.'",
        "Slide 3: 'Named: marginalization. Sum rule. Same move as last week.'",
    ],
)

# Conditional build-up
deck.build_slides(
    title="Conditional — restrict and renormalize",
    steps=[
        [
            ("Chibany weighs today's bento and reads:   D = heavy.",
             {"size": 22, "color": deck.YELLOW}),
            ("What's  P(meal | heavy)?",
             {"size": 24, "bold": True}),
            ("", {"size": 8}),
            ("Same move as Week 1's 2×2 coin-flip grid:",
             {"size": 18, "color": deck.DIM}),
            ("\"Restrict to the slice where the observation is true; renormalize.\"",
             {"size": 18, "color": deck.DIM, "italic": True}),
        ],
        [
            ("", {"size": 10}),
            ("Step 1:   keep only the \"heavy\" column of the joint.",
             {"size": 20}),
            ("   P(tonk, heavy) = 0.63        P(hamb, heavy) = 0.06",
             {"size": 20, "color": deck.ACCENT}),
            ("", {"size": 8}),
            ("Step 2:   renormalize by P(heavy) = 0.69.",
             {"size": 20}),
        ],
        [
            ("", {"size": 8}),
            ("   P(tonk | heavy)   =  0.63 / 0.69  ≈  0.913",
             {"size": 22, "bold": True, "color": deck.GREEN}),
            ("   P(hamb | heavy)  =  0.06 / 0.69  ≈  0.087",
             {"size": 22, "bold": True, "color": deck.GREEN}),
            ("", {"size": 6}),
            ("Prior 0.70 → posterior 0.91. \"Heavy\" was very diagnostic.",
             {"size": 20, "color": deck.DIM, "italic": True}),
        ],
    ],
    notes=[
        "Slide 1: 'Observation arrives. Now ask the conditional question. "
        "This is the SAME move as last week\\'s P(first=H | at least one H) = "
        "2/3 on the coin-flip grid. Restrict and renormalize.'",
        "Slide 2: 'Two steps. Slice the joint to keep only rows consistent "
        "with the observation; renormalize.'",
        "Slide 3: 'Posterior. Observing heavy moved prior 0.70 to posterior "
        "0.91 — strongly diagnostic. Much stronger than the cab problem "
        "(0.15 prior → 0.41 posterior). Why? The likelihoods here are more "
        "informative, and the prior was less extreme.'",
    ],
)

deck.content_slide(
    title="Summary — three operations on the joint",
    body=[
        ("Joint         =  full picture, P(H, D). All cells sum to 1.",
         {"size": 22}),
        ("Marginal   =  sum the joint over the thing you don't care about.",
         {"size": 22}),
        ("Conditional =  slice on your observation, renormalize.",
         {"size": 22}),
        ("", {"size": 10}),
        ("Same Bayes as last week. Now you can SEE it as a table operation.",
         {"size": 22, "bold": True, "color": deck.ACCENT}),
    ],
    notes=(
        "~1 min. Mental model to carry forward. Everything today (and "
        "Week 3) is operations on this table — just with infinitely many cells."
    ),
)

# ============================================================
# BLOCK 5 — Expected value + discrete distributions (15 min)
# ============================================================

deck.agenda_slide(AGENDA, highlight="Expected value + discrete")

deck.section_break(
    segment_name="Expected value + discrete distributions",
    notes=(
        "15 min. E[X] (4 slides), Bernoulli (3 slides), Binomial (4 slides + "
        "1 real PMF image). Bernoulli IS the meal draw; Binomial IS a week."
    ),
)

# E[X]
deck.build_slides(
    title="Expected value  E[X]",
    steps=[
        [
            ("For a discrete RV X with values {xᵢ} and probabilities {pᵢ}:",
             {"size": 20}),
            ("", {"size": 8}),
            ("E[X]  =  Σᵢ  xᵢ · pᵢ",
             {"size": 28, "bold": True, "color": deck.ACCENT}),
            ("", {"size": 6}),
            ("\"Weight each value by its probability, then add.\"",
             {"size": 20, "color": deck.DIM, "italic": True}),
        ],
        [
            ("", {"size": 10}),
            ("Chibany: encode meal numerically.  tonkatsu = 1, hamburger = 0.",
             {"size": 20}),
            ("E[meal]  =  1 · 0.7  +  0 · 0.3  =  0.7",
             {"size": 22, "bold": True}),
            ("", {"size": 6}),
            ("The expected value of an indicator IS the probability.",
             {"size": 22, "color": deck.YELLOW}),
        ],
        [
            ("", {"size": 10}),
            ("Variance:   Var[X]  =  E[(X − E[X])²]  =  E[X²] − E[X]²",
             {"size": 22}),
            ("For Bernoulli(p):   Var  =  p(1 − p)",
             {"size": 22}),
            ("Bento meal:   Var = 0.21,   σ ≈ 0.46",
             {"size": 22, "bold": True}),
        ],
        [
            ("", {"size": 8}),
            ("E[X]  =  center of mass.      Var[X]  =  spread.",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
            ("", {"size": 6}),
            ("Two numbers that summarize a lot. Used everywhere downstream.",
             {"size": 20, "color": deck.DIM}),
        ],
    ],
    notes=[
        "Slide 1: 'Expected value. Weighted average. The formula is what you\\'d "
        "naïvely call an average — but weighted by probability instead of "
        "counted equally.'",
        "Slide 2: 'Encode meal as 1/0. Then E[meal] equals the probability. "
        "Key trick — we use it constantly in RL and in hypothesis testing.'",
        "Slide 3: 'Variance. Spread. For Bernoulli(p), it simplifies to p(1-p). "
        "Maxed at p=0.5; smaller at the extremes.'",
        "Slide 4: 'Mental model: mean = balance point, variance = width.'",
    ],
)

# Bernoulli
deck.build_slides(
    title="Bernoulli distribution",
    steps=[
        [
            ("X ~ Bernoulli(p)     means:",
             {"size": 22}),
            ("    P(X = 1) = p,     P(X = 0) = 1 − p",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
            ("", {"size": 8}),
            ("One flip of a weighted coin. One parameter: p.",
             {"size": 20, "color": deck.DIM}),
        ],
        [
            ("", {"size": 10}),
            ("Chibany: meal_today  ~  Bernoulli(0.7).",
             {"size": 22, "bold": True}),
            ("    P(meal_today = tonkatsu) = 0.7",
             {"size": 22}),
            ("    P(meal_today = hamburger) = 0.3",
             {"size": 22}),
        ],
        [
            ("", {"size": 10}),
            ("Today we treat  p = 0.7  as GIVEN.",
             {"size": 22, "color": deck.DIM}),
            ("Next week: we ask where p comes from, and infer it from data.",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
            ("The conjugate prior on p is the Beta distribution — Week 3.",
             {"size": 20, "color": deck.DIM}),
        ],
    ],
    notes=[
        "Slide 1: 'Bernoulli. One parameter.'",
        "Slide 2: 'The bento meal is Bernoulli(0.7). Every day, a weighted flip.'",
        "Slide 3: 'Flag: in Week 3 we shift gears and INFER p from observed "
        "counts. That\\'s what conjugacy enables — we\\'ll put a prior on p '"
        "(Beta distribution) and use Bayes to update.'",
    ],
)

# Binomial — 3 text build-ups then a real image
deck.build_slides(
    title="Binomial distribution",
    steps=[
        [
            ("Chibany counts tonkatsu across 5 days.",
             {"size": 22}),
            ("Each day:  Bernoulli(0.7), independent.",
             {"size": 22}),
            ("Let Y = total tonkatsu in 5 days.    Y  ~  Binomial(5, 0.7).",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
        ],
        [
            ("", {"size": 8}),
            ("P(Y = k)  =  C(n, k) · pᵏ · (1 − p)ⁿ⁻ᵏ",
             {"size": 26, "bold": True}),
            ("", {"size": 4}),
            ("   n = 5      (trials)",
             {"size": 18, "color": deck.DIM}),
            ("   k          (count of successes)",
             {"size": 18, "color": deck.DIM}),
            ("   p = 0.7   (per-trial success prob)",
             {"size": 18, "color": deck.DIM}),
            ("   C(n, k)   counts orderings of k successes among n trials",
             {"size": 18, "color": deck.DIM}),
        ],
        [
            ("", {"size": 6}),
            ("P(Y = 5)  =  1 · 0.7⁵ · 1         ≈  0.168",
             {"size": 20}),
            ("P(Y = 4)  =  5 · 0.7⁴ · 0.3     ≈  0.360        ← the MODE",
             {"size": 20, "bold": True, "color": deck.YELLOW}),
            ("P(Y = 3)  =  10 · 0.7³ · 0.3²   ≈  0.309",
             {"size": 20}),
            ("", {"size": 8}),
            ("Why is k=4 more likely than k=5,  even though p = 0.7?",
             {"size": 20, "bold": True, "color": deck.ACCENT}),
            ("   There are 5 ways to get 4 tonkatsu in 5 days, but only 1 way to get all 5.",
             {"size": 18, "color": deck.DIM, "italic": True}),
            ("   The extra orderings outweigh the smaller (0.7·0.3) factor.",
             {"size": 18, "color": deck.DIM, "italic": True}),
        ],
    ],
    notes=[
        "Slide 1: 'Zoom out. A single bento is Bernoulli. A WEEK is Binomial. "
        "Y counts successes.'",
        "Slide 2: 'Binomial formula. Name each piece. Binomial coefficient "
        "C(n,k) = \"n choose k\" = count of orderings.'",
        "Slide 3: 'Plug in for k=3, 4, 5. The mode is k=4 — this surprises "
        "students who expect k=5 because p=0.7 > 0.5. The answer: 5 orderings "
        "for k=4 vs 1 ordering for k=5. The combinatorics wins over the extra "
        "factor of 0.7.'",
    ],
)

# Real Binomial PMF image
deck.content_image_slide(
    title="Binomial(5, 0.7) — full PMF",
    image_path=IMG / "binomial_pmf.png",
    caption=[
        ("Mode at k=4 (0.360). In Week 3 this PMF becomes the LIKELIHOOD",
         {"size": 18}),
        ("for inferring  p  from observed counts. Beta × Binomial = Beta.",
         {"size": 18, "color": deck.DIM, "italic": True}),
    ],
    notes=(
        "~1 min. Real bar chart. Let it sit — students can see the shape. "
        "Flag the Week-3 connection: when we don\\'t KNOW p, this PMF with an "
        "unknown p becomes a function of p, and Beta conjugates nicely with it."
    ),
    image_width_in=7.5, image_top_in=1.0,
)

# ============================================================
# BLOCK 6 — Continuous probability + the Gaussian (20 min, with real images)
# ============================================================

deck.agenda_slide(AGENDA, highlight="Continuous prob + Gaussian")

deck.section_break(
    segment_name="Continuous probability + the Gaussian",
    notes=(
        "20 min. Build: PMF→PDF (4 text + 1 image), Gaussian formula "
        "(5 text + 1 image), continuous-Bayes worked (6 text + 1 image). "
        "The images are the payoff — do NOT speak over them; pause."
    ),
)

# PMF → PDF text build-up
deck.build_slides(
    title="From PMF to PDF — going continuous",
    steps=[
        [
            ("Weight isn't heavy-or-light. It's a real number.",
             {"size": 22}),
            ("We need a different object — a probability DENSITY.",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
        ],
        [
            ("", {"size": 10}),
            ("Thought experiment — shrink the bins:",
             {"size": 22}),
            ("    30g bins:   coarse histogram, PMF over bins",
             {"size": 20, "color": deck.DIM}),
            ("    10g bins:   finer, still PMF",
             {"size": 20, "color": deck.DIM}),
            ("     2g bins:   finer still",
             {"size": 20, "color": deck.DIM}),
            ("    bin → 0:   PMF → PDF",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
        ],
        [
            ("", {"size": 8}),
            ("The density  f(x)  is NOT a probability — it's probability PER UNIT.",
             {"size": 22, "bold": True}),
            ("", {"size": 6}),
            ("P(X ∈ [a, b])  =  ∫ₐᵇ f(x) dx       \"area under the density\"",
             {"size": 22, "color": deck.ACCENT}),
            ("", {"size": 6}),
            ("PDF values can exceed 1. Probabilities cannot.",
             {"size": 20, "color": deck.DIM}),
        ],
        [
            ("", {"size": 8}),
            ("Why  P(X = exactly 450g)  =  0   for continuous X:",
             {"size": 22}),
            ("    ∫₄₅₀⁴⁵⁰ f(x) dx  =  0      (integrate over a single point)",
             {"size": 20, "color": deck.DIM}),
            ("", {"size": 6}),
            ("But  P(X ∈ [449.5, 450.5])  ≈  f(450) · 1",
             {"size": 22, "bold": True, "color": deck.GREEN}),
            ("", {"size": 4}),
            ("\"density × interval width = probability.\"",
             {"size": 20, "color": deck.DIM, "italic": True}),
        ],
    ],
    notes=[
        "Slide 1: 'Weight is continuous. No finite outcome space. We need a "
        "new object — the PDF.'",
        "Slide 2: 'Binning thought experiment. Bin the weights. Shrink bins. "
        "In the limit: a smooth curve. That curve is the density.'",
        "Slide 3: 'Density ≠ probability. This trips students up. Density is '"
        "probability PER UNIT. You integrate to get a probability. Density "
        "values can be > 1 (density of N(0, 0.01) at 0 is ~40).'",
        "Slide 4: 'Corollary: probability of ANY exact value is 0 for a "
        "continuous RV. But probability of being near any value is f(x) × "
        "(small interval). Intuitive and mathematically honest.'",
    ],
)

# PMF → PDF visual
deck.content_image_slide(
    title="Shrinking bins → PDF as the limit",
    image_path=IMG / "pmf_to_pdf.png",
    caption=[
        ("Same underlying data, three bin widths. Blue curve: limit (PDF).",
         {"size": 18, "color": deck.DIM}),
    ],
    notes=(
        "Pause 10 seconds. Let them see the histograms smoothing into the "
        "PDF. The blue curve is the same Gaussian in all three panels — the "
        "histograms are approaching it from above and below."
    ),
    image_width_in=8.4, image_top_in=1.1,
)

# Gaussian formula build-up
deck.build_slides(
    title="The Gaussian (normal) distribution",
    steps=[
        [
            ("Chibany's bento weights vary — even within one meal type.",
             {"size": 22}),
            ("Tonkatsu weight is roughly  N(500, 30²)  —  centered at 500, spread ≈ 30g.",
             {"size": 22, "color": deck.ACCENT}),
        ],
        [
            ("", {"size": 8}),
            ("N(x | μ, σ²)   =    ( 1 / √(2π σ²) )  ·  exp( − (x − μ)² / (2σ²) )",
             {"size": 22, "bold": True}),
        ],
        [
            ("", {"size": 8}),
            ("Name each piece:",
             {"size": 20}),
            ("   μ       mean — where the curve peaks",
             {"size": 20, "color": deck.DIM}),
            ("   σ²      variance — how wide the curve is  (σ = std dev)",
             {"size": 20, "color": deck.DIM}),
            ("   exp(−(x−μ)²/(2σ²))    peaks at μ, falls off fast outside ±σ",
             {"size": 20, "color": deck.DIM}),
            ("   1/√(2π σ²)                the normalizer — makes total area = 1",
             {"size": 20, "color": deck.DIM}),
        ],
        [
            ("", {"size": 6}),
            ("Shape facts:",
             {"size": 22, "bold": True}),
            ("   • symmetric around μ",
             {"size": 20}),
            ("   • peak height = 1/√(2π σ²) — sharper curves are TALLER",
             {"size": 20}),
            ("   • ~68% of mass within  μ ± σ;    ~95% within  μ ± 2σ",
             {"size": 20}),
        ],
        [
            ("", {"size": 8}),
            ("Chibany's two bento-weight distributions:",
             {"size": 22, "bold": True}),
            ("   tonkatsu weight     ~   N(500, 30²)",
             {"size": 22, "color": deck.ACCENT}),
            ("   hamburger weight  ~   N(350, 30²)",
             {"size": 22, "color": deck.ACCENT}),
            ("", {"size": 6}),
            ("Two bell curves. They overlap in the middle — that's where 450g lives.",
             {"size": 20, "color": deck.DIM, "italic": True}),
        ],
    ],
    notes=[
        "Slide 1: 'Real bentos vary. Not every tonkatsu is exactly 500g. The "
        "natural distribution for that variation is the Gaussian.'",
        "Slide 2: 'The formula. Don\\'t try to hold the whole thing at once — "
        "we\\'ll name each piece now.'",
        "Slide 3: 'Four pieces. Mean, variance, the exponential (which does "
        "the peaking), and the normalizer (which makes the area equal 1 — '"
        "required of any PDF).'",
        "Slide 4: 'Shape. Symmetric around μ. SHARPER (smaller σ) → TALLER "
        "peak. The 68-95-99.7 rule — most mass within 1, 2, 3 sigma.'",
        "Slide 5: 'Two Gaussians for Chibany. They overlap in the 380-470 "
        "range. Next slide: picture.'",
    ],
)

# Gaussian shape image
deck.content_image_slide(
    title="The Gaussian — shape and the 68-95 rule",
    image_path=IMG / "gaussian_shape.png",
    caption=[
        ("Dark fill: ±1σ (~68%). Light fill: ±2σ (~95%).",
         {"size": 18, "color": deck.DIM}),
    ],
    notes=(
        "Pause. Let them trace the curve and see the shaded bands. The peak "
        "height formula 1/√(2πσ²) ≈ 0.013 for σ=30 — visible at the top."
    ),
    image_width_in=8.4, image_top_in=1.1,
)

# Tonkatsu/hamburger likelihoods image
deck.content_image_slide(
    title="Chibany's two bento-weight likelihoods",
    image_path=IMG / "tonk_hamb.png",
    caption=[
        ("Yellow line: observed 450g. Closer to tonkatsu, but within hamburger tail.",
         {"size": 18, "color": deck.DIM}),
    ],
    notes=(
        "Key setup image for the continuous-Bayes worked example that "
        "follows. 450g sits squarely in the tonkatsu Gaussian, far in the "
        "right tail of hamburger. The next slide computes the densities."
    ),
    image_width_in=8.4, image_top_in=1.1,
)

# Continuous-Bayes build-up
deck.build_slides(
    title="Bayes with a continuous likelihood — worked",
    steps=[
        [
            ("Today's observation:   D  =  weight  =  450g.",
             {"size": 22, "bold": True, "color": deck.YELLOW}),
            ("", {"size": 8}),
            ("What's  P(meal | weight = 450g) ?",
             {"size": 22}),
        ],
        [
            ("", {"size": 8}),
            ("Prior stays discrete:    P(tonkatsu) = 0.7,   P(hamburger) = 0.3",
             {"size": 20}),
        ],
        [
            ("", {"size": 8}),
            ("Likelihood is a Gaussian density:",
             {"size": 20}),
            ("   f_T  =  N(450 | 500, 30²)",
             {"size": 20}),
            ("          =  (1/√(2π·900)) · exp(−(−50)²/1800)",
             {"size": 18, "color": deck.DIM}),
            ("          =  0.01330 · exp(−1.389)     ≈   0.00332",
             {"size": 20, "bold": True, "color": deck.ACCENT}),
            ("   f_H  =  N(450 | 350, 30²)     ≈   0.00044",
             {"size": 20, "bold": True, "color": deck.ACCENT}),
            ("", {"size": 4}),
            ("Density values, not probabilities. (Integral → probability.)",
             {"size": 16, "color": deck.DIM, "italic": True}),
        ],
        [
            ("", {"size": 8}),
            ("Numerator   =   prior · likelihood:",
             {"size": 20}),
            ("   tonkatsu:     0.7 · 0.00332   =   0.00232",
             {"size": 20}),
            ("   hamburger:  0.3 · 0.00044   =   0.000132",
             {"size": 20}),
            ("", {"size": 6}),
            ("Evidence   =   sum   =   0.00246",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
        ],
        [
            ("", {"size": 6}),
            ("Posterior:",
             {"size": 20}),
            ("   P(tonkatsu | 450g)    =  0.00232 / 0.00246   ≈  0.946",
             {"size": 22, "bold": True, "color": deck.GREEN}),
            ("   P(hamburger | 450g) =  0.000132 / 0.00246  ≈  0.054",
             {"size": 22, "bold": True, "color": deck.GREEN}),
        ],
        [
            ("", {"size": 6}),
            ("Prior → Posterior:      0.70  →  0.946   (tonkatsu)",
             {"size": 22, "bold": True}),
            ("                                   0.30  →  0.054   (hamburger)",
             {"size": 22, "bold": True}),
            ("", {"size": 4}),
            ("Block 4 coarse (heavy-vs-light):     0.70 → 0.91",
             {"size": 20, "color": deck.DIM}),
            ("Block 6 continuous (exact weight):  0.70 → 0.95",
             {"size": 20, "color": deck.DIM}),
            ("Exact continuous value is more informative than a bucket.",
             {"size": 20, "color": deck.YELLOW, "italic": True}),
        ],
    ],
    notes=[
        "Slide 1: 'New observation: actual weight, 450g. Same Bayesian "
        "question.'",
        "Slide 2: 'Prior unchanged — still 0.7/0.3 on meal.'",
        "Slide 3: 'The work: compute each Gaussian density value. I\\'m "
        "showing the arithmetic for f_T: the normalizer coefficient ≈ 0.0133, "
        "the exponent is −(−50)²/1800 = −1.389, exp of that is 0.249, product "
        "≈ 0.00332. f_H comes out to 0.00044 — much smaller because 450 is "
        "far from 350.'",
        "Slide 4: 'Multiply prior by likelihood. Sum for the evidence.'",
        "Slide 5: 'Divide. Posterior is 0.95/0.05.'",
        "Slide 6: 'Compare to Block 4 (heavy/light bucketing): 0.91. The "
        "continuous exact value moves belief further because it uses the "
        "precise weight, not just a bucket.'",
    ],
)

# ============================================================
# BREAK
# ============================================================

deck.break_slide(
    text="Break — 10 minutes",
    notes=(
        "Hard 10. Block 7 is the highest-stakes block of the session. Come "
        "back sharp. Double-check the tonk_hamb.png loaded correctly on the "
        "projector."
    ),
)

# ============================================================
# BLOCK 7 — Gaussian-Gaussian update (25 min)
# ============================================================

deck.agenda_slide(AGENDA, highlight="Gaussian-Gaussian update")

deck.section_break(
    segment_name="Gaussian-Gaussian update — launching Week 3",
    notes=(
        "25 min. THE block of the session. Now with: (a) explicit motivation "
        "for inferring μ, (b) a derivation SKETCH (complete the square), "
        "(c) a real posterior-curve picture, (d) precision visualized, "
        "(e) N-observation generalization given its own build-up."
    ),
)

# Motivation — why infer μ
deck.build_slides(
    title="Why would Chibany want to infer μ ?",
    steps=[
        [
            ("So far Chibany asks:  \"what's in TODAY's bento?\"",
             {"size": 22}),
            ("   Today's weight, 450g  →  posterior over today's meal.",
             {"size": 20, "color": deck.DIM}),
        ],
        [
            ("", {"size": 10}),
            ("But to DO that well, Chibany needs to know:",
             {"size": 22, "bold": True}),
            ("   How much DO tonkatsu bentos typically weigh?",
             {"size": 22, "color": deck.YELLOW}),
            ("   (We wrote \"500\" as if it were known. But is it?)",
             {"size": 20, "color": deck.DIM, "italic": True}),
        ],
        [
            ("", {"size": 8}),
            ("Shift in perspective:",
             {"size": 22, "bold": True}),
            ("   • Yesterday's Bayes:   H = today's MEAL  (discrete hypothesis)",
             {"size": 20}),
            ("   • Today's Bayes:        H = tonkatsu's MEAN WEIGHT μ  (continuous parameter)",
             {"size": 20, "color": deck.ACCENT}),
            ("", {"size": 8}),
            ("Why Bayesian inference on μ instead of just averaging?",
             {"size": 20, "italic": True}),
            ("  Because Chibany has PRIOR knowledge (last semester), plus LIMITED data.",
             {"size": 20, "color": deck.DIM}),
            ("  Averaging throws the prior away. Bayes combines both.",
             {"size": 20, "color": deck.DIM}),
        ],
    ],
    notes=[
        "Slide 1: 'Up to now, the question has been about today\\'s meal. "
        "A discrete hypothesis.'",
        "Slide 2: 'But we wrote 500g as if we KNEW it. We don\\'t really. "
        "This term is an unknown PARAMETER. Call it μ.'",
        "Slide 3: 'So now Bayesian inference is shifting: H = μ, a continuous "
        "parameter, not a discrete category. Why not just average the "
        "weights? Because Chibany has prior knowledge from past experience, "
        "and early in the semester they have very few data points. "
        "Averaging is what a frequentist would do and it discards the prior. '"
        "Bayes keeps both.'",
    ],
)

# Prior
deck.build_slides(
    title="Step 1 — the prior  μ ~ N(μ₀, σ₀²)",
    steps=[
        [
            ("Chibany's belief about μ BEFORE observing any new weights:",
             {"size": 22}),
            ("", {"size": 8}),
            ("   μ  ~  N(μ₀, σ₀²)",
             {"size": 28, "bold": True, "color": deck.ACCENT}),
            ("", {"size": 4}),
            ("\"I think μ is around μ₀, give or take σ₀.\"",
             {"size": 20, "color": deck.DIM, "italic": True}),
        ],
        [
            ("", {"size": 8}),
            ("From last semester's memory:",
             {"size": 20}),
            ("   μ₀ = 500  (best guess)        σ₀ = 20  (uncertainty)",
             {"size": 22, "bold": True}),
            ("", {"size": 4}),
            ("Prior:   μ  ~  N(500, 20²)",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
        ],
        [
            ("", {"size": 8}),
            ("The conceptual leap:   priors over PARAMETERS.",
             {"size": 22, "bold": True, "color": deck.YELLOW}),
            ("", {"size": 6}),
            ("The Gaussian is NOT over weights now. It's over μ.",
             {"size": 22}),
            ("A prior is a distribution over anything hidden —",
             {"size": 22}),
            ("including parameters of OTHER distributions.",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
        ],
    ],
    notes=[
        "Slide 1: 'Prior is a Gaussian over μ. Two hyperparameters: μ₀ and σ₀.'",
        "Slide 2: 'Chibany\\'s best guess 500, uncertainty 20. Prior = N(500, "
        "400).'",
        "Slide 3: 'THIS IS THE BIG MOVE. The density isn\\'t over weights now. '"
        "It\\'s over the unknown parameter μ. Priors can live on parameters. "
        "In Week 4 we\\'ll even put a prior on the PRIOR — hierarchical Bayes.'",
    ],
)

# Likelihood
deck.build_slides(
    title="Step 2 — the likelihood",
    steps=[
        [
            ("Chibany weighs one bento:   D₁ = 510g.",
             {"size": 22, "bold": True, "color": deck.YELLOW}),
            ("(Assume σ = 30 is known — we infer μ only.)",
             {"size": 20, "color": deck.DIM}),
        ],
        [
            ("", {"size": 10}),
            ("Likelihood:",
             {"size": 22}),
            ("   P(D₁ = 510 | μ)   =   N(510 | μ, 30²)",
             {"size": 24, "bold": True, "color": deck.ACCENT}),
        ],
        [
            ("", {"size": 10}),
            ("As a function of  μ,  this is ALSO a Gaussian —",
             {"size": 22, "bold": True}),
            ("peaked at  μ = 510,  width σ = 30.",
             {"size": 22, "bold": True}),
            ("", {"size": 8}),
            ("So we have two Gaussian functions of μ:",
             {"size": 22, "color": deck.ACCENT}),
            ("   prior          (peaked at 500, tight)",
             {"size": 20}),
            ("   likelihood   (peaked at 510, broader)",
             {"size": 20}),
        ],
    ],
    notes=[
        "Slide 1: 'One observation. 510g. We pretend σ is known — only μ is "
        "unknown. Week 3 will relax this.'",
        "Slide 2: 'Likelihood is the Gaussian density evaluated at the '"
        "observed weight, as a function of μ.'",
        "Slide 3: 'Here\\'s the trick: when you treat the likelihood N(D|μ,σ²) "
        "as a function of μ for fixed D, it\\'s STILL a Gaussian shape — "
        "peaked where μ=D. So we have two Gaussians in μ. Multiplying them "
        "is the Bayes step.'",
    ],
)

# DERIVATION SKETCH (new — replaces "MAGIC")
deck.build_slides(
    title="Why Gaussian × Gaussian = Gaussian  (derivation sketch)",
    steps=[
        [
            ("Multiply the two densities (drop the normalizers — collect at end):",
             {"size": 20}),
            ("", {"size": 6}),
            ("  P(μ|D) ∝ exp( −(μ − μ₀)² / 2σ₀² )   ·   exp( −(D − μ)² / 2σ² )",
             {"size": 20, "bold": True}),
        ],
        [
            ("", {"size": 8}),
            ("Combine exponents:",
             {"size": 20}),
            ("  ∝  exp( − [ (μ − μ₀)² / 2σ₀²  +  (D − μ)² / 2σ² ] )",
             {"size": 20, "bold": True}),
            ("", {"size": 6}),
            ("The thing in [ ] is a quadratic in μ — A·μ² − 2B·μ + const.",
             {"size": 20, "color": deck.DIM}),
        ],
        [
            ("", {"size": 8}),
            ("Complete the square → exp( −(μ − μ_post)² / 2σ²_post )  +  const.",
             {"size": 20, "bold": True}),
            ("", {"size": 6}),
            ("That's the kernel of a Gaussian in μ.  Posterior is Gaussian.",
             {"size": 22, "bold": True, "color": deck.GREEN}),
        ],
        [
            ("", {"size": 6}),
            ("The new mean and variance come from matching coefficients:",
             {"size": 20}),
            ("", {"size": 4}),
            ("  1 / σ²_post   =   1/σ₀²   +   1/σ²              (coefficient of μ²)",
             {"size": 22, "bold": True}),
            ("  μ_post         =   σ²_post · (μ₀/σ₀² + D/σ²)        (coefficient of μ)",
             {"size": 22, "bold": True}),
            ("", {"size": 6}),
            ("Full derivation: textbook T3 Ch 4 — read this week.",
             {"size": 18, "color": deck.DIM, "italic": True}),
        ],
    ],
    notes=[
        "Slide 1: 'Multiply the two Gaussian densities. Normalizers are "
        "constants in μ — we absorb them into the final normalization later.'",
        "Slide 2: 'Expand the squared terms and combine. You get a quadratic "
        "in μ. Form: Aμ² − 2Bμ + constants.'",
        "Slide 3: 'Complete the square — just like in high school algebra. "
        "A quadratic in μ inside an exp is the kernel of a Gaussian. So the "
        "posterior IS Gaussian. Not magic — algebra.'",
        "Slide 4: 'The new μ and σ come from matching coefficients. A "
        "(coefficient of μ²) gives you 1/σ²_post. B/A (the minimum of the "
        "quadratic) gives you μ_post. Full derivation in T3 Ch 4 — read it.'",
    ],
)

# Precision image + concept
deck.content_image_slide(
    title="Precision  =  1 / variance  =  \"how sharp I am\"",
    image_path=IMG / "precision.png",
    caption=[
        ("Sharper curve = higher precision = more confident (more weight in the update).",
         {"size": 18, "color": deck.DIM}),
    ],
    notes=(
        "Pause. Two Gaussians, same mean, different widths. The sharp one is "
        "more precise — if you\\'re that sharp, you\\'re very sure, and in a "
        "Bayesian update your view gets more weight. Intuition for the "
        "precision-sum formula on the next slide."
    ),
    image_width_in=8.4, image_top_in=1.1,
)

# Posterior build-up with real numbers (now 6 steps, ending with N-obs preview)
deck.build_slides(
    title="Plug in the numbers  —  posterior  =  prior × likelihood, rescaled",
    steps=[
        [
            ("The update formulas  (from the derivation):",
             {"size": 20, "bold": True}),
            ("", {"size": 4}),
            ("   1 / σ²_post  =  1/σ₀²  +  1/σ²",
             {"size": 22, "bold": True}),
            ("   μ_post         =  σ²_post · ( μ₀/σ₀² + D/σ² )",
             {"size": 22, "bold": True}),
            ("", {"size": 6}),
            ("Intuition:   precisions add.  μ_post = precision-weighted average.",
             {"size": 20, "color": deck.YELLOW, "italic": True}),
        ],
        [
            ("", {"size": 8}),
            ("Numbers:",
             {"size": 22}),
            ("   σ₀² = 400   (prior),    σ² = 900   (data),    μ₀ = 500,    D = 510",
             {"size": 20}),
        ],
        [
            ("", {"size": 6}),
            ("Posterior variance:",
             {"size": 22}),
            ("   1/σ²_post  =  1/400  +  1/900  =  9/3600 + 4/3600  =  13/3600",
             {"size": 20}),
            ("", {"size": 4}),
            ("   σ²_post   ≈   277              σ_post   ≈   16.6",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
            ("", {"size": 4}),
            ("Tighter than both inputs (20 and 30). Adding precisions REDUCES uncertainty.",
             {"size": 18, "color": deck.GREEN, "italic": True}),
        ],
        [
            ("", {"size": 6}),
            ("Posterior mean:",
             {"size": 22}),
            ("   μ_post  =  277 · ( 500/400  +  510/900 )",
             {"size": 20}),
            ("              =  277 · ( 1.250  +  0.567 )",
             {"size": 20}),
            ("              =  277 · 1.817    ≈    503.1",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
            ("", {"size": 4}),
            ("Moved from prior (500) toward data (510), but stayed closer to prior",
             {"size": 18, "color": deck.DIM, "italic": True}),
            ("— because prior precision (1/400) > data precision (1/900).",
             {"size": 18, "color": deck.DIM, "italic": True}),
        ],
    ],
    notes=[
        "Slide 1: 'The formulas. Precisions add. Posterior mean is precision-"
        "weighted average.'",
        "Slide 2: 'The inputs.'",
        "Slide 3: 'Posterior variance. 1/400 + 1/900 combines on 3600. Gets "
        "you 13/3600, so σ²_post ≈ 277, σ_post ≈ 16.6. TIGHTER than either "
        "input. Combining information reduces uncertainty — that\\'s the "
        "whole point of Bayesian updating.'",
        "Slide 4: 'Posterior mean ≈ 503.1. Moved from 500 toward 510 but "
        "mostly stayed near the prior. Because the prior was more precise "
        "(σ₀=20 vs data σ=30). The more precise source wins.'",
    ],
)

# GG posterior picture
deck.content_image_slide(
    title="Prior × Likelihood = Posterior",
    image_path=IMG / "gg_update.png",
    caption=[
        ("Red = prior. Blue = likelihood. Yellow = posterior (tighter; between both).",
         {"size": 18, "color": deck.DIM}),
    ],
    notes=(
        "THE payoff visual. Pause. Red prior, blue likelihood, yellow "
        "posterior. The posterior IS tighter than both inputs and lives "
        "between them — closer to the prior because the prior is tighter. "
        "This one picture replaces 20 minutes of algebra in students\\' "
        "memory."
    ),
    image_width_in=8.5, image_top_in=1.1,
)

# N observations generalization (its own build-up)
deck.build_slides(
    title="N observations  —  precisions keep adding",
    steps=[
        [
            ("One observation:   precision added = 1/σ².",
             {"size": 22}),
            ("Two observations: precision added = 2/σ².",
             {"size": 22}),
            ("N observations:    precision added = N/σ².",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
        ],
        [
            ("", {"size": 10}),
            ("   1 / σ²_post   =   1/σ₀²   +   N/σ²",
             {"size": 24, "bold": True}),
            ("", {"size": 6}),
            ("   μ_post          =   σ²_post · ( μ₀/σ₀²  +  Σᵢ Dᵢ / σ² )",
             {"size": 24, "bold": True}),
        ],
        [
            ("", {"size": 8}),
            ("As N grows:",
             {"size": 22}),
            ("   • 1/σ²_post  →  ∞        (posterior gets sharp)",
             {"size": 20}),
            ("   • μ_post       →  mean of observed weights      (data dominates)",
             {"size": 20}),
            ("", {"size": 6}),
            ("More data  →  sharper posterior, pulled toward sample mean.",
             {"size": 22, "bold": True, "color": deck.YELLOW}),
            ("This single formula underlies much of Weeks 3 and 4.",
             {"size": 20, "color": deck.DIM, "italic": True}),
        ],
    ],
    notes=[
        "Slide 1: 'Each independent observation adds precision 1/σ². Two "
        "observations = 2/σ² added. N observations = N/σ². This is the key "
        "property of conjugate updates.'",
        "Slide 2: 'The general formulas. Σ_i D_i is the sum of observed "
        "weights.'",
        "Slide 3: 'Asymptotic behavior: as N grows, the prior term becomes "
        "negligible and the posterior mean approaches the sample mean. You "
        "recover the frequentist answer in the limit of much data — but "
        "with a Bayesian path there, and a well-calibrated posterior variance '"
        "along the way. This formula IS the skeleton of Week 3\\'s conjugate "
        "updates and Week 4\\'s hierarchical models.'",
    ],
)

# Close Block 7
deck.build_slides(
    title="Closing the arc — same Bayes, new objects",
    steps=[
        [
            ("Block 4:   H discrete, D discrete.   Joint is a 4-cell table.",
             {"size": 22}),
            ("Block 6:   H discrete, D continuous.   Likelihood is a density.",
             {"size": 22}),
            ("Block 7:   H continuous, D continuous.   Prior, likelihood, posterior",
             {"size": 22}),
            ("                all densities. Updates via precision arithmetic.",
             {"size": 22}),
            ("", {"size": 6}),
            ("Same Bayes rule throughout.  The OBJECTS generalized.",
             {"size": 22, "bold": True, "color": deck.ACCENT}),
        ],
        [
            ("", {"size": 8}),
            ("The named move:   CONJUGACY.",
             {"size": 26, "bold": True, "color": deck.YELLOW}),
            ("", {"size": 6}),
            ("Gaussian × Gaussian  =  Gaussian         (today)",
             {"size": 22}),
            ("Beta × Binomial  =  Beta                      (Week 3)",
             {"size": 22, "color": deck.ACCENT}),
            ("Dirichlet × Multinomial  =  Dirichlet       (Week 3)",
             {"size": 22, "color": deck.ACCENT}),
            ("", {"size": 6}),
            ("Conjugacy = algebra works out; the posterior stays in the prior's family.",
             {"size": 20, "color": deck.DIM, "italic": True}),
        ],
    ],
    notes=[
        "Slide 1: 'Zoom out. Three flavors of Bayes today. Same rule, "
        "progressively more general objects.'",
        "Slide 2: 'Named: conjugacy. Today was Gaussian-Gaussian. Week 3 we "
        "do it on the discrete side (Beta-Binomial, Dirichlet-Multinomial). "
        "Beta × Binomial gives Beta — try to see what\\'s on your tongue re "
        "Bayesian inference on a coin\\'s p.'",
    ],
)

# ============================================================
# BLOCK 8 — Paper presentations (10 min)
# ============================================================

deck.agenda_slide(AGENDA, highlight="Paper presentations")

deck.section_break(
    segment_name="Paper presentations — rubric + signup",
    notes="10 min tight.",
)

deck.content_slide(
    title="Presentations — why and what",
    body=[
        ("Enrollment is 6.  Each of you presents ONCE.",
         {"size": 24, "bold": True}),
        ("20 min presentation + 10-15 min discussion you facilitate.",
         {"size": 22}),
        ("7.5% of grade.  Reflections dropped 15% → 12.5% to make room.",
         {"size": 20, "color": deck.DIM}),
        ("", {"size": 10}),
        ("Meet with me in office hours the week before your slot.",
         {"size": 22, "bold": True, "color": deck.ACCENT}),
    ],
    notes="~2 min.",
)

deck.content_slide(
    title="Rubric — 5 points",
    body=[
        ("Understanding of the paper              1.5",
         {"size": 22}),
        ("Covering key aspects                      1.5",
         {"size": 22}),
        ("Presentation clarity                         1.0",
         {"size": 22}),
        ("Discussion questions (at least 3)        0.5",
         {"size": 22}),
        ("Appropriate use of time                    0.5",
         {"size": 22}),
        ("", {"size": 8}),
        ("Focus: how the math connects to cognitive science.",
         {"size": 20, "color": deck.DIM, "italic": True}),
        ("Full guidelines:  resources/classPresentationGuidelines.pdf  (emailed today).",
         {"size": 18, "color": deck.DIM}),
    ],
    notes="~2 min. Email the PDF.",
)

deck.content_slide(
    title="Signup — Weeks 4 through 12",
    body=[
        ("9 slots, 6 students. Three stay open for contemporary-ML content.",
         {"size": 22, "color": deck.DIM}),
        ("", {"size": 6}),
        ("  Week  4 (May 22)  —  Generalization + hierarchical Bayes",
         {"size": 18}),
        ("  Week  5 (May 29)  —  Bayes nets + causal Bayes nets",
         {"size": 18}),
        ("  Week  6 (Jun  5)  —  Markov chains + networks",
         {"size": 18}),
        ("  Week  7 (Jun 12)  —  Monte Carlo",
         {"size": 18}),
        ("  Week  8 (Jun 19)  —  SDT / MDP / RL",
         {"size": 18}),
        ("  Week  9 (Jun 26)  —  Inverse RL",
         {"size": 18}),
        ("  Week 10 (Jul  3)  —  Bayesian nonparametrics",
         {"size": 18}),
        ("  Week 11 (Jul 10)  —  Deep NNs",
         {"size": 18}),
        ("  Week 12 (Jul 17)  —  Ethics + adversarial ML + project presentations",
         {"size": 18, "color": deck.DIM}),
    ],
    notes="~6 min. Signups on the board. Photograph; transcribe into readings_map.yml.",
)

# ============================================================
# BLOCK 9 — Admin + Week 3 homework (10 min)
# ============================================================

deck.agenda_slide(AGENDA, highlight="Admin + Week 3")

deck.section_break(
    segment_name="Admin + Week 3 homework",
    notes="10 min.",
)

deck.content_slide(
    title="Syllabus — three things changed",
    body=[
        ("① 12 sessions, not 13.",
         {"size": 24, "bold": True}),
        ("    No class May 1 AND May 8. Week 3 is Friday May 15.",
         {"size": 20, "color": deck.DIM}),
        ("", {"size": 6}),
        ("② Reflections: 6 of 12, not 8 of 13.",
         {"size": 24, "bold": True}),
        ("    ~200 words, pre-class, pass/fail.",
         {"size": 20, "color": deck.DIM}),
        ("", {"size": 6}),
        ("③ Paper presentations exist → 7.5%.",
         {"size": 24, "bold": True}),
        ("    Reflections dropped 15% → 12.5% to make room.",
         {"size": 20, "color": deck.DIM}),
    ],
    notes="~3 min.",
)

deck.content_slide(
    title="Week 3 — readings + homework",
    body=[
        ("Next class:   Friday May 15  —  Week 3: Conjugate Bayes + Topics.",
         {"size": 22}),
        ("", {"size": 10}),
        ("Required reading:",
         {"size": 22, "bold": True}),
        ("  • Textbook T3 Ch 1   (Chibany's mystery bentos — the full story)",
         {"size": 20}),
        ("  • Textbook T3 Ch 4   (Bayesian learning with Gaussians)",
         {"size": 20}),
        ("     — formalizes what we did in Block 7.",
         {"size": 18, "color": deck.DIM, "italic": True}),
        ("", {"size": 6}),
        ("Ungraded self-check: \"Intro Probability Theory 1\" quiz.",
         {"size": 20, "color": deck.DIM}),
    ],
    notes=(
        "~4 min. T3 Ch 1 is added so Chibany\\'s backstory is reinforced; T3 "
        "Ch 4 derives what we sketched in Block 7."
    ),
)

deck.content_slide(
    title="Preview — the arc from here",
    body=[
        ("Week 3:  Conjugacy proper.  Beta-Binomial + Gaussian-Gaussian.",
         {"size": 22}),
        ("Week 4:  Hierarchical Bayes.  Chibany's distribution of tonkatsu rates.",
         {"size": 22}),
        ("Week 5:  Bayes nets + causal.",
         {"size": 22}),
        ("", {"size": 8}),
        ("Weeks 6-7:  Markov chains, Monte Carlo  (sampling-based L2).",
         {"size": 20, "color": deck.DIM}),
        ("Weeks 8-10:  Decision, RL, IRL, nonparametrics.",
         {"size": 20, "color": deck.DIM}),
        ("Weeks 11-12:  Deep NNs, ethics  —  contemporary ML.",
         {"size": 20, "color": deck.DIM}),
        ("", {"size": 6}),
        ("Thanks — see you May 15.",
         {"size": 22, "bold": True, "color": deck.ACCENT}),
    ],
    notes="~3 min. Close warm.",
)

# ============================================================
# Save and export
# ============================================================

PPTX_OUT.parent.mkdir(parents=True, exist_ok=True)
deck.save(str(PPTX_OUT))
deck.export_notes_md(str(NOTES_OUT), title="Week 2: Speaker Notes")
if args.preview:
    deck.render_previews(str(PPTX_OUT), str(PREVIEW_OUT), dpi=args.dpi)
